#162162968 Implement rate article
andela/ah-frontend-poseidon pull request #22
Opened 2019-01-21 15:12 UTC by katunold

#### What does this PR do?
- Implement rate article feature.
- Implement an article rating display.
- Write tests for rate article feature

2019-01-28 15:10 UTC, kizzanaome approved these changes

2019-01-28 23:33 UTC, arthurarty requested changes

2019-01-28 23:33 UTC, arthurarty commented on public/index.html
> +    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
@katunold I noticed on this line you are adding a jquery library. However, in the package.json file jquery 3.3.1 is listed as a dependency. Are there any advantages jquery 1.11.12 brings to the project?   Is there any advantage of importing like this as opposed to installing it as a package?

2019-01-28 23:33 UTC, arthurarty commented on src/redux/thunks/index.js
> +      console.log(response.data);
@katunold I noticed a console.log on this line.

2019-01-29 06:18 UTC, katunold commented on public/index.html
> +    <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
I was using it before but am not using it anymore, let me just kick it out

2019-01-29 06:22 UTC, katunold commented on src/redux/thunks/index.js
> +      console.log(response.data);
All clear now

2019-01-29 07:42 UTC, arthurarty approved these changes

2019-01-29 09:55 UTC, merged