#162162967 Users should be able to create articles
andela/ah-frontend-poseidon pull request #25
Opened 2019-01-23 17:07 UTC by Luleherll

**What does this PR do?**
- Add redux thunks for getting and posting data
- Create article reducer function

**Description of the tasks to be completed?**
- Update the `types` file in the actions folder.
- Modify `ArticleReducer` file in reducers file
- Create rich text editor
- Create article components

**How to manually test it**
- Clone the repository by running `git clone https://github.com/andela/ah-frontend-poseidon.git`
- Run `git checkout ft-create-articles-162162967`
- Start the server by running `yarn start`

**Screenshots**
<img width="1440" alt="screen shot 2019-01-23 at 6 53 01 pm" src="https://user-images.githubusercontent.com/36928255/51621591-ec597180-1f45-11e9-86c8-fbf9fc1bf8bb.png">
<img width="1440" alt="screen shot 2019-01-23 at 6 52 27 pm" src="https://user-images.githubusercontent.com/36928255/51621605-f54a4300-1f45-11e9-9bd6-dc828179dda4.png">
<img width="1440" alt="screen shot 2019-01-23 at 6 53 10 pm" src="https://user-images.githubusercontent.com/36928255/51621613-f9766080-1f45-11e9-8f7d-0871be7c5674.png">

**What are the relevant pivotal tracker stories?**
#162162967

2019-01-23 17:33 UTC, arthurarty approved these changes

2019-01-23 17:35 UTC, arthurarty approved these changes

2019-01-24 06:03 UTC, katunold commented
Well done @Luleherll, Please squash your commits

2019-01-24 06:17 UTC, katunold requested changes

2019-01-24 06:17 UTC, katunold commented on src/components/articles/Editor.jsx
> +}
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/components/articles/Tags.jsx
> +}
@Luleherll, please add an empty line at the end of this file too

2019-01-24 06:17 UTC, katunold commented on src/components/articles/__tests__/EditorTest.js
> +});
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/components/dashboard/ArticleComponent.jsx
> +export default Article;
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/components/dashboard/Dashboard.scss
> +}
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/components/dashboard/NavBarComponent.jsx
> +export default NavBar;
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/components/dashboard/SideBarComponent.jsx
> +export default SideBar
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/redux/thunks/__tests__/ThunksTest.js
> +});
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:17 UTC, katunold commented on src/views/homeView.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(HomeView)
@Luleherll, please add an empty line at the end of this file

2019-01-24 06:37 UTC, katunold requested changes

2019-01-24 06:37 UTC, katunold commented on src/components/articles/Articles.jsx
> +export default connect(mapStateToProps, mapDispatchToProps)(ArticleView)
@Luleherll, you forgot to an empty line at the end of this file.

2019-01-24 06:37 UTC, katunold commented on src/components/articles/articles.scss
> +}
This too needs an empty line at the end of the file.

2019-01-24 06:44 UTC, katunold approved these changes

2019-01-24 07:27 UTC, okellogabrielinnocent approved these changes

2019-01-24 07:29 UTC, billkabanga approved these changes

2019-01-24 15:59 UTC, aayebare approved these changes
I've tested this. The functionality works fine. Great work Lule

2019-01-24 16:41 UTC, merged