#162162971 Users should be able to Like and Dislike An Article
andela/ah-frontend-poseidon pull request #32
Opened 2019-01-27 22:23 UTC by kizzanaome

### What does this PR do?
- Enable user to like or dislike an article.

### Description of Task to be completed?
- Create LikeDislike component
- Add Like and Dislike icons to the Article component

### How should this be manually tested?
- Clone the repository by running git clone https://github.com/andela/ah-frontend-poseidon.git
- Run git checkout  ft-dislike-like-article-162162971
- Start the server by running yarn start
- Navigate to the articles page, and click ReadMore, to display an article.
- You will be able to like/dislike that article

### What are the relevant pivotal tracker stories?
#162162971

### Screenshot

![image](https://user-images.githubusercontent.com/29730491/51839956-c227fb00-231b-11e9-8438-180b72ae4049.png)

2019-01-28 15:02 UTC, billkabanga approved these changes

2019-01-28 15:05 UTC, katunold approved these changes

2019-01-28 15:57 UTC, arthurarty approved these changes

2019-01-28 23:36 UTC, arthurarty commented on src/components/articles/LikeDislikeComponent.jsx
> +            { color: likeColor, width: '80px', height: '30px' },
@kizzanaome I noticed styling on line 26 which is very similar to they styling online 32. What do you think of having a css class that has this css and then adding the class to both icons.

2019-01-28 23:40 UTC, arthurarty reviewed
@kizzanaome What you think of having a css class to handle your styling for the like and disklike button.

2019-01-29 07:18 UTC, kizzanaome commented on src/components/articles/LikeDislikeComponent.jsx
> +            { color: likeColor, width: '80px', height: '30px' },
Okay, Thanks for pointing that out let me fix it.

2019-01-29 08:57 UTC, kizzanaome commented on src/components/articles/LikeDislikeComponent.jsx
> +            { color: likeColor, width: '80px', height: '30px' },
I have fixed this

2019-01-29 16:33 UTC, Luleherll requested changes
I have tested the feature and I think the page should not reload when a user likes because we would be resetting the state. Please look through @katunold and @m-asiimwe's implementation.

2019-01-29 16:47 UTC, kizzanaome commented
@Luleherl l  sorted that issue already.

2019-01-29 17:02 UTC, Luleherll commented
> @Luleherl l sorted that issue already.

I first pulled before I tested, maybe you had not pushed the code. Am going to pull again and test it out.

2019-01-30 05:56 UTC, Luleherll approved these changes

2019-01-30 05:59 UTC, Luleherll commented
Nice work @kizzanaome. Please also squash the commits.

2019-01-30 08:52 UTC, merged